import os
import json
import smtplib
import hashlib
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, Optional
from dataclasses import dataclass, asdict
from jira import JIRA
from dotenv import load_dotenv

load_dotenv()

# ─────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────

JIRA_SERVER = os.getenv("JIRA_SERVER", "https://your-domain.atlassian.net")
JIRA_EMAIL = os.getenv("JIRA_EMAIL")
JIRA_API_TOKEN = os.getenv("JIRA_API_TOKEN")
JIRA_PROJECT_KEY = os.getenv("JIRA_PROJECT_KEY", "SCRUM")

SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_EMAIL = os.getenv("SMTP_EMAIL")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
MANAGER_EMAIL = os.getenv("MANAGER_EMAIL")

APP_BASE_URL = os.getenv("APP_BASE_URL", "http://localhost:8501")


# ─────────────────────────────────────────────
# Data Models
# ─────────────────────────────────────────────

@dataclass
class BugTicket:
    title: str
    description: str
    severity: str
    failure_type: str
    steps_to_reproduce: str
    suggested_assignee: str
    error_pattern: str
    log_source: str
    status: str = "pending_approval"
    ticket_id: Optional[str] = None
    approval_token: Optional[str] = None

    def to_dict(self) -> Dict:
        return asdict(self)

    def generate_token(self) -> str:
        raw = f"{self.title}{self.error_pattern}{time.time()}"
        self.approval_token = hashlib.sha256(raw.encode()).hexdigest()[:16]
        return self.approval_token


# ─────────────────────────────────────────────
# Jira Client
# ─────────────────────────────────────────────

class JiraClient:
    def __init__(self):
        self.client = JIRA(
            server=JIRA_SERVER,
            basic_auth=(JIRA_EMAIL, JIRA_API_TOKEN)
        )

    def create_bug(self, ticket: BugTicket) -> str:
        severity_map = {
            "Critical": "Highest",
            "High": "High",
            "Medium": "Medium",
            "Low": "Low"
        }

        description = (
            f"*Failure Type:* {ticket.failure_type}\n"
            f"*Severity:* {ticket.severity}\n"
            f"*Error Pattern:*\n{{code}}{ticket.error_pattern}{{code}}\n\n"
            f"*Description:*\n{ticket.description}\n\n"
            f"*Steps to Reproduce:*\n{ticket.steps_to_reproduce}\n\n"
            f"*Log Source:* {ticket.log_source}\n\n"
            f"----\n"
            f"_Auto-generated by AI Log Analyzer & QA Intelligence Platform_"
        )

        fields = {
            "project": {"key": JIRA_PROJECT_KEY},
            "summary": ticket.title,
            "description": description,
            "issuetype": {"name": "Task"},
            "labels": ["ai-generated", ticket.failure_type.replace(" ", "-")],
        }

        # Try to assign the ticket
        if ticket.suggested_assignee:
            try:
                users = self.client.search_users(query=ticket.suggested_assignee)
                if users:
                    fields["assignee"] = {"accountId": users[0].accountId}
            except Exception:
                pass

        issue = self.client.create_issue(fields=fields)
        ticket.ticket_id = issue.key
        ticket.status = "created"
        return issue.key

    def get_project_members(self) -> list:
        try:
            members = self.client.search_assignable_users_for_projects(
                "", JIRA_PROJECT_KEY
            )
            return [m.displayName for m in members]
        except Exception:
            return []


# ─────────────────────────────────────────────
# Email Service
# ─────────────────────────────────────────────

class EmailService:
    def __init__(self):
        self.server = SMTP_SERVER
        self.port = SMTP_PORT
        self.email = SMTP_EMAIL
        self.password = SMTP_PASSWORD

    def send_approval_email(self, ticket: BugTicket, manager_email: str, token: str = None) -> bool:
        if not token:
            token = ticket.approval_token or ticket.generate_token()

        approve_url = f"{APP_BASE_URL}?action=approve&token={token}"
        reject_url = f"{APP_BASE_URL}?action=reject&token={token}"

        severity_colors = {
            "Critical": "#dc3545",
            "High": "#fd7e14",
            "Medium": "#ffc107",
            "Low": "#28a745"
        }
        color = severity_colors.get(ticket.severity, "#6c757d")

        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px; background-color: #f5f5f5;">
            <div style="max-width: 600px; margin: 0 auto; background: #fff; border-radius: 8px;
                        box-shadow: 0 2px 8px rgba(0,0,0,0.1); overflow: hidden;">

                <div style="background: #1a1a2e; color: #fff; padding: 20px; text-align: center;">
                    <h2 style="margin: 0;">AI Log Analyzer</h2>
                    <p style="margin: 5px 0 0; opacity: 0.8;">Bug Ticket Approval Request</p>
                </div>

                <div style="padding: 25px;">
                    <h3 style="margin-top: 0; color: #333;">{ticket.title}</h3>

                    <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
                        <tr>
                            <td style="padding: 8px 12px; border: 1px solid #eee; font-weight: bold;
                                       background: #f8f9fa; width: 140px;">Severity</td>
                            <td style="padding: 8px 12px; border: 1px solid #eee;">
                                <span style="background: {color}; color: #fff; padding: 3px 10px;
                                             border-radius: 4px; font-size: 13px;">{ticket.severity}</span>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding: 8px 12px; border: 1px solid #eee; font-weight: bold;
                                       background: #f8f9fa;">Failure Type</td>
                            <td style="padding: 8px 12px; border: 1px solid #eee;">{ticket.failure_type}</td>
                        </tr>
                        <tr>
                            <td style="padding: 8px 12px; border: 1px solid #eee; font-weight: bold;
                                       background: #f8f9fa;">Assignee</td>
                            <td style="padding: 8px 12px; border: 1px solid #eee;">{ticket.suggested_assignee}</td>
                        </tr>
                        <tr>
                            <td style="padding: 8px 12px; border: 1px solid #eee; font-weight: bold;
                                       background: #f8f9fa;">Error Pattern</td>
                            <td style="padding: 8px 12px; border: 1px solid #eee;">
                                <code style="background: #f1f1f1; padding: 2px 6px;">{ticket.error_pattern}</code>
                            </td>
                        </tr>
                    </table>

                    <div style="background: #f8f9fa; padding: 12px; border-radius: 6px; margin: 15px 0;">
                        <strong>Description:</strong><br>
                        <p style="margin: 8px 0 0;">{ticket.description}</p>
                    </div>

                    <div style="background: #f8f9fa; padding: 12px; border-radius: 6px; margin: 15px 0;">
                        <strong>Steps to Reproduce:</strong><br>
                        <p style="margin: 8px 0 0;">{ticket.steps_to_reproduce}</p>
                    </div>

                    <div style="text-align: center; margin: 25px 0 10px;">
                        <a href="{approve_url}" style="display: inline-block; padding: 12px 35px;
                           background: #28a745; color: #fff; text-decoration: none; border-radius: 6px;
                           font-weight: bold; margin: 0 10px;">Approve & Create Ticket</a>
                        <a href="{reject_url}" style="display: inline-block; padding: 12px 35px;
                           background: #dc3545; color: #fff; text-decoration: none; border-radius: 6px;
                           font-weight: bold; margin: 0 10px;">Reject</a>
                    </div>

                    <p style="color: #888; font-size: 12px; text-align: center; margin-top: 20px;">
                        This is an automated email from AI Log Analyzer & QA Intelligence Platform.
                    </p>
                </div>
            </div>
        </body>
        </html>
        """

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[QA Approval] {ticket.severity} Bug: {ticket.title}"
        msg["From"] = self.email
        msg["To"] = manager_email
        msg.attach(MIMEText(html_body, "html"))

        try:
            with smtplib.SMTP(self.server, self.port) as server:
                server.starttls()
                server.login(self.email, self.password)
                server.sendmail(self.email, manager_email, msg.as_string())
            return True
        except Exception as e:
            print(f"Email send failed: {e}")
            return False

    def send_ticket_created_notification(self, ticket: BugTicket, manager_email: str) -> bool:
        jira_url = f"{JIRA_SERVER}/browse/{ticket.ticket_id}"

        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
            <div style="max-width: 500px; margin: 0 auto; background: #fff; border-radius: 8px;
                        padding: 25px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
                <div style="text-align: center; margin-bottom: 15px;">
                    <span style="font-size: 40px;">&#9989;</span>
                </div>
                <h3 style="text-align: center; color: #28a745;">Jira Ticket Created Successfully</h3>
                <p style="text-align: center;">
                    <strong>{ticket.ticket_id}</strong>: {ticket.title}
                </p>
                <div style="text-align: center; margin: 20px 0;">
                    <a href="{jira_url}" style="display: inline-block; padding: 10px 30px;
                       background: #0052cc; color: #fff; text-decoration: none; border-radius: 6px;
                       font-weight: bold;">View in Jira</a>
                </div>
            </div>
        </body>
        </html>
        """

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[QA] Ticket Created: {ticket.ticket_id} - {ticket.title}"
        msg["From"] = self.email
        msg["To"] = manager_email
        msg.attach(MIMEText(html_body, "html"))

        try:
            with smtplib.SMTP(self.server, self.port) as server:
                server.starttls()
                server.login(self.email, self.password)
                server.sendmail(self.email, manager_email, msg.as_string())
            return True
        except Exception as e:
            print(f"Confirmation email failed: {e}")
            return False


# ─────────────────────────────────────────────
# LLM Bug Report Generator
# ─────────────────────────────────────────────

def generate_bug_ticket_from_analysis(
    error_pattern: str,
    error_count: int,
    associated_commands: str,
    log_source: str,
    llm_model,
) -> BugTicket:
    prompt = f"""
    Analyze this error from CI/CD logs and generate a structured bug report.

    Error Pattern: {error_pattern}
    Occurrences: {error_count}
    Associated Commands: {associated_commands}
    Log Source: {log_source}

    Respond ONLY in valid JSON with these exact keys:
    {{
        "title": "concise bug title under 80 chars",
        "description": "detailed description of the issue",
        "severity": "Critical or High or Medium or Low",
        "failure_type": "environment or code_defect or flaky_test or data_issue",
        "steps_to_reproduce": "step by step reproduction",
        "suggested_assignee": "team or role suggestion like Backend Team or DevOps Team"
    }}
    """

    response = llm_model.invoke(prompt)
    raw = response.content.replace("```json", "").replace("```", "").strip()
    data = json.loads(raw)

    return BugTicket(
        title=data["title"],
        description=data["description"],
        severity=data["severity"],
        failure_type=data["failure_type"],
        steps_to_reproduce=data["steps_to_reproduce"],
        suggested_assignee=data["suggested_assignee"],
        error_pattern=error_pattern,
        log_source=log_source,
    )


# ─────────────────────────────────────────────
# Persistent Ticket Store (JSON file)
# ─────────────────────────────────────────────

TICKET_STORE_FILE = os.path.join(os.path.dirname(__file__), "pending_tickets.json")


class TicketStore:
    def __init__(self, filepath: str = TICKET_STORE_FILE):
        self.filepath = filepath
        self._ensure_file()

    def _ensure_file(self):
        if not os.path.exists(self.filepath):
            with open(self.filepath, "w") as f:
                json.dump({}, f)

    def _load(self) -> Dict[str, dict]:
        try:
            with open(self.filepath, "r") as f:
                return json.load(f)
        except (json.JSONDecodeError, FileNotFoundError):
            return {}

    def _save(self, data: Dict[str, dict]):
        with open(self.filepath, "w") as f:
            json.dump(data, f, indent=2)

    def add(self, ticket: BugTicket) -> str:
        token = ticket.generate_token()
        data = self._load()
        data[token] = ticket.to_dict()
        self._save(data)
        return token

    def get(self, token: str) -> Optional[BugTicket]:
        data = self._load()
        entry = data.get(token)
        if entry:
            return BugTicket(**entry)
        return None

    def approve(self, token: str) -> Optional[BugTicket]:
        data = self._load()
        entry = data.get(token)
        if entry:
            entry["status"] = "approved"
            self._save(data)
            return BugTicket(**entry)
        return None

    def reject(self, token: str) -> Optional[BugTicket]:
        data = self._load()
        entry = data.get(token)
        if entry:
            entry["status"] = "rejected"
            del data[token]
            self._save(data)
            return BugTicket(**entry)
        return None

    @property
    def pending(self) -> Dict[str, BugTicket]:
        data = self._load()
        return {
            token: BugTicket(**entry)
            for token, entry in data.items()
            if entry.get("status") == "pending_approval"
        }


ticket_store = TicketStore()